AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Update Me

Globals:
  Api:
    BinaryMediaTypes:
      - application~1pdf

Resources:
  # Define an API GateWay
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Staging
    BinaryMediaTypes:
      - application~1pdf
    # BinaryMediaTypes:
    #   - '*~1*'
    # DefinitionBody:
    #   x-amazon-apigateway-binary-media-types:
    #     - '*/*'

  # Define the consumer Lambda function and EventBridge rule
  PdfFunction:
    Type: AWS::Serverless::Function
    Description: Invoked by EventBridge scheduled rule
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs18.x
      Timeout: 15
      MemorySize: 3008

      Layers:
        - !Sub 'arn:aws:lambda:us-east-1:764866452798:layer:chrome-aws-lambda:22'
        - !Sub 'arn:aws:lambda:us-east-1:923560778095:layer:chromium:1'
      Environment:
        Variables:
          EXAMPLE_ENV: 'CHANGE_THIS'
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /pdf
            Method: get
            RestApiId:
              Ref: ApiGatewayApi
Outputs:
  ApiGatewayApi:
    Description: API Gateway endpoint URL for Staging stage for Hello World function
    Value:
      Fn::Sub: https://${ApiGatewayApi}.execute-api.${AWS::Region}.amazonaws.com/Staging/
